### ISSUE TITLE
关于 yaml解析遇到的问题

### ISSUE THREAD

**Issue by tank411** [gookit/config#10]
在解析yaml时候遇到了解析出错：
yam文件格式如下：

```yml
---
id: VEHICLE-RFID-0807112517
name: vehicle rfid pipeline
properties:
  kafka.bootstrap.servers: hdh98:9092,hdh197:9092,hdh199:9092
  kafka.zookeeper.connector: hdh98:2181,hdh197:2181,hdh199:2181
  hbase.zookeeper.quorum: hdh98:2181,hdh197:2181,hdh199:2181
  hbase.zookeeper.property.clientPort: 2181

```

查看了错误原因是因为解析时候对key的分割处理导致的。
read.go 文件中，144行处。

```go
	if !strings.Contains(key, ".") {
		// c.addError(errNotFound)
		return
	}

	keys := strings.Split(key, ".")
	topK := keys[0]
```

修改后：

```go
	if !strings.Contains(key, ":") {
		// c.addError(errNotFound)
		return
	}

	keys := strings.Split(key, ":")
	topK := keys[0]
```

在解析文件中希望可以修改，修改后查询使用的方式如下：
`value2 := cfg.String("topics:0:properties:cleanup.policy")`
