### ISSUE TITLE
yaml Binding ist not working correctly

### ISSUE THREAD

**Issue by mgcos1231** [gookit/config#140]
**System (please complete the following information):**

 - OS: `macOS` 
 - GO Version: `go version go1.20.1 darwin/amd64` 
 - Pkg Version: `v2.2.1` 

**Describe the bug**

yaml Binding ist not working correctly

**To Reproduce**

```yaml 
server:
  portNumber: 8080

oauth2:
  redirectUrl:  "http://localhost:8080/login/oauth2/code/dbwebsso",
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  scopes:
    - "1234/.default"
    - "openid"
    - "profile"
    - "email"
  endPoint: "1234"

```
```go
package myConfig

import (
	"fmt"
	"github.com/gookit/config/v2"
	"github.com/gookit/config/v2/yamlv3"
)

type Binder struct {
	Server server `mapstructure:"server"`
	Oauth2 oauth2 `mapstructure:"oauth2"`
}

type server struct {
	PortNumber string `mapstructure:"portNumber"`
}

type oauth2 struct {
	RedirectUrl  string   `mapstructure:"redirectUrl"`
	ClientId     string   `mapstructure:"clientId"`
	ClientSecret string   `mapstructure:"clientSecret"`
	Scopes       []string `mapstructure:"scopes"`
	EndPoint     string   `mapstructure:"endPoint"`
}

var MyConfig Binder

func LoadConfig() {

	config.WithOptions(config.ParseEnv)

	// only add decoder
	// config.SetDecoder(config.Yaml, yamlv3.Decoder)
	// Or
	config.AddDriver(yamlv3.Driver)

	err := config.LoadFiles("config/config.yml")
	if err != nil {
		panic(err)
	}

	config.BindStruct("", &MyConfig)
	//fmt.Printf("config data: \n %#v\n", config.Data())
	fmt.Printf("config data: \n %v\n", MyConfig)
}

```

Output
```
config data: 
 {{8080} {http://localhost:8080/login/oauth2/code/dbwebsso   [] }}

```

**Expected behavior**

Object Binding is working properly. If I am doing wrong, i am please to get example.
