### ISSUE TITLE
监听文件变更，删除配置信息未改变

### ISSUE THREAD

**Issue by zuozhehao** [gookit/config#152]
```
test:
  data1:
    key: value
  data2:
    key: value
```
当删除一组配置信息的时
```
test:
  data1:
    key: value
```
监听到文件变更，`cfg.Data()`读出来的还是两组信息，data1和data2
