### ISSUE TITLE
Consider the notion of profiles/environments for configuration files

### ISSUE THREAD

**Issue by x80486** [gookit/config#155]
## Description

Loading and binding configuration data to Go's `struct`s is probably all within the scope of this library, but I think that almost always, any modern application is delivered throughout different environments. Moreover, following this is a premise for any application that follows the _twelve-factor_ methodology.

I think it would be great if gookit's config supports this in a certain way. For instance:

```yaml
---
application:
  key: default_value___useless_because_it_s_overwritten_in_all_environments
datasource:
  username: postgres # Common to all, unless overwritten
---
"%dev":
  application:
    key: value_for_dev
  datasource:
    password: postgres_secret_for_dev
    url: postgresql:host-for-dev:5432/database
---
"%prod":
  application:
    key: value_for_production
  datasource:
    username: postgres_in_prod
    password: postgres_secret_for_prod
    url: postgresql:host-for-prod:5432/database
---
"%test":
  application:
    key: value_for_test
  datasource:
    password: postgres_secret_for_test
    url: postgresql:host-for-test:5432/database
```

Currently the only way to achieve this is to make use of environment variables, and that's a viable route, but it gets really messy when an application uses a lot of configuration settings — like the one I'm dealing with :grimacing:
