### ISSUE TITLE
Fail fast for required values

### ISSUE THREAD

**Issue by x80486** [gookit/config#156]
I'm integrating `gookit/config` in an existing project in order to manage the configuration. I've ran into some issues, but I've been able to workaround them in one way or another — I'm pretty new to `Go` as well :grimacing:

What I've been able to do is to be able to interrupt the application bootstrapping when there is a missing value. For instance, consider the following configuration:

```yaml
---
datasource:
  password: ${DATABASE_PASSWORD|unset}
  type: postgres
  username: ${DATABASE_USERNAME|postgres}
  url: ${DATABASE_URL|unset}
```

It would be great to have the behavior that `Docker Compose` [provides](https://docs.docker.com/compose/environment-variables/env-file/) to fail whenever a value for an environment variable is not present. Basically, if implemented exactly the same (bonus points!) the YAML file would be like this:

```yaml
---
datasource:
  password: ${DATABASE_PASSWORD|?error}
  type: postgres
  username: ${DATABASE_USERNAME|postgres}
  url: ${DATABASE_URL|?error}
```
